export const LIMITS = {
	MAX: {
		FIELD_LENGTH: {
			BANK_ACCOUNT: {
				ACCOUNT_NAME: 50,
				ACCOUNT_NUMBER: 15,
				BSB: 6,
			},
			DISPLAY_NAME: 50,
			EMAIL_ADDRESS: 254,
			NAMES: 50,
			REGISTRATION: {
				DRIVERS_LICENSE: 9,
				MOBILE_NUMBER: 15,
				PASSPORT_NUMBER: 9,
				RESIDENTIAL_ADDRESS: 255,
				TFN: 9,
			},
		},
	},
	MIN: {
		AGE: 18,
		FIELD_LENGTH: {
			NAMES: 2,
		},
	},
};
